CREATE TABLE tbTicketProyectoBryan (
uuid VARCHAR2(50),
tituloTicket VARCHAR2(30),
descripcionTicket VARCHAR2(30),
responsableTicket VARCHAR(30),
emailContactador VARCHAR2(30),
telefonoContactador VARCHAR2(9),
ubicacionContactador VARCHAR2(30)
);

CREATE TABLE tbUsuariosProyectoBryan (
    idUsuario NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombreUsuario VARCHAR2(50) NOT NULL,
    correo VARCHAR2(100) NOT NULL,
    claveUsuario VARCHAR2(100) NOT NULL,
    PRIMARY KEY (idUsuario)
);

SELECT * FROM tbTicketProyectoBryan

SELECT * FROM tbUsuariosProyectoBryan

drop table tbTicketProyectoBryan

drop table tbUsuariosProyectoBryan